### PR TITLE
Make it buildable

### PR DESCRIPTION
**Pull request by mcatanzaro**
You might not want the "wpewebkit: Remove the multimedia package" commit, because that is a nice package and it's just a workaround due to me not being able to figure out a way to fix that package to not prevent the main WebKit package from being built. But I wanted to include it here in order to provide a complete set of commits that are needed to build.

The final commit "Don't set options unnecessarily" doesn't actually do anything, it's just a cleanup, but the others were all needed for me.

### CODE REVIEW

**Comment by mcatanzaro** [comment]
And now Carlos has got ENABLE_WEBDRIVER working and made it public, so we probably don't need to remove that package anymore. (Though I have not tried to build it yet.)

**Comment by aperezdc** [comment]
@mcatanzaro: I added the WebDriver option preventively, copied over from the WebKitGTK+ build recipe, because I was expecting it would be available eventually. I will try to set aside some time in the next days to go over your comments. I have already locally fixed the issue with the recursive dependency of the Multimedia support option. At any rate, thanks a lot for trying out the patch set and providing valuable feedback :+1:

**Comment by mcatanzaro** [comment]
OK cool. Note: only the first commit (adding aarch64 support) and last commit (dropping a bunch of unnecessary options) are still desirable. Although we should probably expose ENABLE_API_TESTS instead of dropping it now that Carlos has that working.

**Comment by mcatanzaro** [comment]
Sorry, ENABLE_API_TESTS is not exposed by GTK either, and it's turned on by ENABLE_DEVELOPER_MODE, so there is no need to unset it here, because DEVELOPER_MODE is not used. I'll close this and open two new PRs.

**Comment by mcatanzaro** [comment]
Oh, I see you already added aarch64 support... in that case, my only remaining commit that's relevant is the commit to clean up the unneeded build options. So you'll get one new pull request, and the rest of this is now stale.

**Comment by mcatanzaro** [comment]
Also, heads up: this comment:

`# ARM needs BLX, so v5t+, BE completely untested so disabled`

is now stale, because you removed the code to disable it on ARM big endian (both 32-bit and 64-bit).

**Pull request closed without merging**
